name: user_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.2.1
  english_words: ^4.0.0
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.1.5
  validators: ^3.0.0
  flutter_riverpod: ^1.0.4
  either_dart: ^0.1.4
  cached_network_image: ^3.2.1
  flutter_widget_from_html_core: ^0.8.5+3
  shimmer: ^2.0.0
  humanizer: ^2.0.0
  #  apk_admin: 2.2.4
#  google_mobile_ads: ^1.2.0
  timer_count_down: ^2.2.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

